### PR TITLE
Fix update mechanic on RollOptions with merged suboptions

### LINKED ISSUE #17015: Change Shape RE gets stuck with identical suboptions from different sources
If the Myriad Forms Ancestry Feat is added to a Kitsune PC, the Change Shape Roll Option gets stuck at some point (typically after selecting Fox or Tailless).

This seems to be caused by identical suboptions from different sources. In this case the fox or taillless suboption, which is already added by the Heritage or Ancestry. Removing the duplicate suboption from the Myriad Forms RE fixes the problem for this PC.

I'll make a PR in a moment. It's just a little cleanup of the REs but it provides a workaround for Kitsune to this behavior.

### LINKED ISSUE #17857: Kitsune "Change Shape" Drop down issues with Myriad Forms
**Build:** 331
**PF2e Vers:** 6.8.1

**Issue:** Kitsune drop down on action tab for Current Form overwrites selected option once Myriad Forms is selected as an Ancestry Feat. See Below:

### Before Myriad Forms
Sheet without Myriad Forms: Tailless and Humanoid as expected for a Kitsune with Palace Echoes heritage. Myriad Forms not added to sheet yet.
image
image
image
image

### After Myriad Forms
"Fox" is added to drop down as expected, but attempting to change between forms by selecting a different row is overwritten. Clicking from Fox to Tailless swaps it back to Fox instantly. Clicking Tailless again makes it seem like it "sticks", but closing the sheet and reopening it shows that it is still on "Fox".
image

### LINKED ISSUE #17932: Werecreature Change Shape broken when taken on a Beastkin Heritage PC
It seems that when you change to an animal form on a Beastkin PC it seems to get stuck in animal form with no way of changing it back to hybrid or humanoid.

Steps:

* Create a new PC with the Beastkin heritage
* Level up PC to level 2 
* Add Werecreature Dedication to class feat section
* Change Current Form drop down in actions to animal
* Change Current Form to Hybrid or Humanoid

Changing the drop down multiple times seems to change it to the correct value sometimes, but it's not persisted on the actor it seems. Even worse: removing the werecreature dedication greys out the drop down since the persisted values probably don't line up

### PR DESCRIPTION
**Pull request by KaitoKuroba**
Closes #17015
Closes #17857
Closes #17932

If a new suboption is selected, all related `RollOptions` are updated. However, `#resolveSuboptions` is used to select the affected rules, which first filters out duplicates. This can result in individual `RuleElements` not being passed and therefore not being updated. During subsequent processing, these `RuleElements` then overwrite the new selection with the old value.

This PR adds a separate method `#resolveSuboptionRules` to find all `RollOptions` of the same family, replacing `#resolveSuboptions` in the update process.

### CODE REVIEW

File: src/module/rules/rule-element/roll-option/rule-element.ts [hunk 1]
```diff
@@ -193,6 +193,24 @@ class RollOptionRuleElement extends RuleElementPF2e<RollOptionSchema> {
...
+                  (r) =>
+                      r instanceof RollOptionRuleElement &&
+                      r.toggleable &&
+                      r.mergeable &&
+                      r.domain === this.domain &&
+                      r.option === this.option,
+              )
+            : [];
+
+        return rules;
```
Comment (stwlam) [inline src/module/rules/rule-element/roll-option/rule-element.ts:211]:
```suggestion
        return this.actor.rules.filter(
              (r) =>
                  r instanceof RollOptionRuleElement &&
                  r.toggleable &&
                  r.mergeable &&
                  r.domain === this.domain &&
                  r.option === this.option,
          );
```
