### PR TITLE
Fix incorrect condition theme on initial load

### LINKED ISSUE #8599: [Bug] The Black and White Condition Icon Set loads the Full Color Set
Foundry Version: 11.305
PF2e Version: 5.1.1
Modules: None

Issue: The "Full Color" Condition Icon set will load when "Black and White" is selected. This seems to happen when a condition has been left on an actor and the page refreshes. This doesnt appear to apply to newly introduced conditions and does load the correct icon if the condition changes

Reproduction Steps:
Create a new world with the Pathfinder Second Edition Game System
Set the "Condition Icon Set" under Pathfinder 2nd Edition Game Settings to "Black and White"
Drag the "Wolf" from NPC (Beastiary 1)" onto the scene
Apply the "Slowed" condition to it
Refresh the page
Note that the Icon for Slowed on the Wolf is now the Full Color Image

### PR DESCRIPTION
**Pull request by CarlosFdez**
Closes #8599

### CODE REVIEW

File: src/module/canvas/status-effects.ts [hunk 1]
```diff
@@ -23,14 +23,6 @@ export class StatusEffects {
...
 
-    /** Set the theme for condition icons on tokens */
-    static setIconTheme(): void {
-        const iconTheme = game.settings.get("pf2e", "statusEffectType");
-        CONFIG.PF2E.statusEffects.lastIconTheme = iconTheme;
-        CONFIG.PF2E.statusEffects.iconDir = this.#ICON_THEME_DIRS[iconTheme];
-        this.#updateStatusIcons();
-    }
-
     /** Link status effect icons to conditions */
```
Comment (stwlam) [inline src/module/canvas/status-effects.ts:26]:
```suggestion
    /** Set the theme for condition icons on tokens */
```
