### PR TITLE
Fix error when enriching null strings

### LINKED ISSUE #3873: Select NPCs Won't Open
image

Any way to recover these or am I going to have to rebuild affected NPCs from scratch? Most NPCs are not affected, but I cannot find what might have been in common between characters that are having this issue.

### PR DESCRIPTION
**Pull request by CarlosFdez**
The built in text editor enrich is able to handle null. Our override was not. Fixes #3873 

Though I'm uncertain if we even need this bit of code here.

### CODE REVIEW

File: src/module/system/text-editor.ts [hunk 1]
```diff
@@ -16,10 +16,10 @@ class TextEditorPF2e extends TextEditor {
     static override enrichHTML(content?: string, options?: EnrichHTMLOptionsPF2e): string;
     static override enrichHTML(
         this: typeof TextEditor,
-        content = "",
+        content?: string,
```
Comment (stwlam) [inline src/module/system/text-editor.ts:19]:
```suggestion
        content?: string | null,
```

**Comment by stwlam** [comment]
:smiley:
