### PR TITLE
Fix editing price from `KitSheetPF2e`

### LINKED ISSUE #19798: Unable to set price of new kit items
Whenever you create a new kit item, the item cannot be updated to set the pricing.

UPDATE - Further testing reveals that once a kit has a Storage item embedded, you cannot remove the container by any means short of altering the JSON file.

### PR DESCRIPTION
**Pull request by stwlam**
Plus minor tidying pass

- Closes #19798

### CODE REVIEW

File: src/module/item/kit/sheet.ts [hunk 1]
```diff
@@ -88,10 +77,9 @@ class KitSheetPF2e extends ItemSheetPF2e<KitPF2e> {
 
     protected override async _updateObject(event: Event, formData: Record<string, unknown>): Promise<void> {
         // Convert price from a string to an actual object
-        if (formData["system.price.value"]) {
-            formData["system.price.value"] = CoinsPF2e.fromString(String(formData["system.price.value"]));
-        }
-
+        const priceString = String(formData["system.price.value"] ?? "").trim();
+        formData["==system.price.value"] = CoinsPF2e.fromString(priceString).toObject();
+        delete formData["system.price.value"];
```
Comment (stwlam) [inline src/module/item/kit/sheet.ts:82]: Actual fix here!
