### PR TITLE
Find macro strike by item id instead of strike slug

### LINKED ISSUE #6366: Dual Wielding similar weapons weapons
When you equip two weapons (say, short swords) that have different runes or unique properties too them, macros attempting to use the weapons fail. This causes a few other addons to fail. 

How to replicate:
1) Create a player character
2) Put 2 identical single handed weapons into the character's inventory (each quantity 1)
2a) (optional) rename the weapons. I will refer to them as weapon1 and weapon2
3) on weapon1, give it a +1 rune (or any other rune)
4) Equip weapon1 and weapon2 in one hand
5) in the actions tab drag the icons for weapon1 and weapon2 down to the macro bar, creating a macro

The macros should have the names:
Strike: weapon1
Strike: weapon2

However, clicking strike: weapon2 will use weapon 1 to strike. 

(alternatively)
-instead of 5, use Token Action HUD (a popular module) to attempt to strike with weapon2, and you will always strike with weapon1

### PR DESCRIPTION
**Pull request by In3luki**
Repurposes the now unused `actorId` to contain the item id of the strike origin with a fallback to strike slug for backwards compatibility.

Closes #6366

### CODE REVIEW

File: src/scripts/macros/hotbar.ts [hunk 1]
```diff
@@ -68,16 +68,16 @@ export async function createActionMacro(actionIndex: number, actorId: string, sl
...
     const speaker = ChatMessage.getSpeaker();
     const actor = canvas.tokens.get(speaker.token ?? "")?.actor ?? game.actors.get(speaker.actor ?? "");
     if (!actor?.isOfType("character", "npc")) {
         return ui.notifications.error("PF2E.MacroActionNoActorError", { localize: true });
     }
 
     const strikes: StrikeData[] = actor.system.actions;
-    const strike = strikes.find((s) => s.slug === actionSlug);
-    if (strike?.slug !== actionSlug) {
+    const strike = strikes.find((s) => s.origin?.id === itemId) ?? strikes.find((s) => s.slug === actionSlug);
```
Comment (stwlam) [inline src/scripts/macros/hotbar.ts:79]:
```suggestion
    const strike = strikes.find((s) => s.item.id === itemId) ?? strikes.find((s) => s.slug === actionSlug);
```

File: src/scripts/macros/hotbar.ts [hunk 2]
```diff
@@ -46,13 +46,13 @@ export function rollItemMacro(itemId: string): ReturnType<ItemPF2e["toChat"]> |
...
 
-export async function createActionMacro(actionIndex: number, actorId: string, slot: number): Promise<void> {
+export async function createActionMacro(actionIndex: number, _actorId: string, slot: number): Promise<void> {
     const speaker = ChatMessage.getSpeaker();
     const actor = canvas.tokens.get(speaker.token ?? "")?.actor ?? game.actors.get(speaker.actor ?? "");
     const action = actor?.isOfType("character", "npc") ? actor.system.actions[actionIndex] : null;
     if (!action) return;
     const macroName = `${game.i18n.localize("PF2E.WeaponStrikeLabel")}: ${action.label}`;
-    const command = `game.pf2e.rollActionMacro("${actorId}", ${actionIndex}, "${action.slug}")`;
+    const command = `game.pf2e.rollActionMacro("${action.origin?.id}", ${actionIndex}, "${action.slug}")`;
```
Comment (stwlam) [inline src/scripts/macros/hotbar.ts:55]:
```suggestion
    const command = `game.pf2e.rollActionMacro("${action.item.id}", ${actionIndex}, "${action.slug}")`;
```

File: src/scripts/macros/hotbar.ts [hunk 3]
```diff
@@ -46,13 +46,13 @@ export function rollItemMacro(itemId: string): ReturnType<ItemPF2e["toChat"]> |
     return item.toChat();
 }
 
-export async function createActionMacro(actionIndex: number, actorId: string, slot: number): Promise<void> {
+export async function createActionMacro(actionIndex: number, _actorId: string, slot: number): Promise<void> {
```
Comment (stwlam) [inline src/scripts/macros/hotbar.ts:49]: We can change the parameters of this freely since it's only used to create new macros

**Comment by In3luki** [comment]
Should be good now.
