### PR TITLE
Fix handling of `null` values in `UUIDUtils.fromUUIDs`

### LINKED ISSUE #8023: Deleting Custom Items Causes Errors opening Actors with the item in Crafting.
To reproduce:
1. Create an Actor.
2. Create a new equipment item (armor, weapon etc...)
3. Drag to the Actor's Crafting Tab.
4. Close Actor
5. Delete from Items tab.
6. Attempt to open Actor.

image

You can reopen the actor after deleting the offending crafting entry after exporting the actor as a json.

Possibly related: Users that had custom items in the crafting tabs of actors have been unable to open them after upgrading to 4.12.4

In 4.12.3, after deleting the item, the actor still opens.

### PR DESCRIPTION
**Pull request by In3luki**
Closes #8023

### CODE REVIEW

File: src/util/uuid.ts [hunk 1]
```diff
@@ -19,7 +19,7 @@ class UUIDUtils {
     /** Retrieve multiple documents by UUID */
     static async fromUUIDs(uuids: string[]): Promise<ClientDocument[]> {
         uuids = R.uniq(uuids);
-        const documentsAndIndexData = uuids.map((u) => fromUuidSync(u));
+        const documentsAndIndexData = R.compact(uuids.map((u) => fromUuidSync(u)));
```
Comment (stwlam) [inline src/util/uuid.ts:22]:
```suggestion
        const documentsAndIndexData = uuids.flatMap((u) => fromUuidSync(u) ?? []);
```
