### PR TITLE
Fix some reported v13 issues

### LINKED ISSUE #18909: 7.0.3-alpha: Undo damage button in chat not doing anything
Image

Most likely the event listener is does not pick up clicks, maybe because the chat log id was changed?

### LINKED ISSUE #18911: 7.0.3-alpha: The icon to pop out all actors from the party actor hud is gone
The icon to pop out all actors from the party actor hud is gone

Image

### PR DESCRIPTION
**Pull request by In3luki**
- Closes #18909 
- Closes #18911

### CODE REVIEW

File: src/scripts/hooks/render-token-hud.ts [hunk 1]
```diff
@@ -13,7 +13,7 @@ export class RenderTokenHUD {
 
             // Remove conditions hud from army. Once Foundry supports replacing these by actor type we'll add them back in
             if (token?.actor?.isOfType("army")) {
-                htmlQuery(html, ".control-icon[data-action=effects]")?.remove();
+                htmlQuery(html, ".control-icon[data-pallette=effects]")?.remove();
```
Comment (simonward) [inline src/scripts/hooks/render-token-hud.ts:16]: Should this be `data-palette=effects`?

Comment (In3luki) [reply src/scripts/hooks/render-token-hud.ts:16]: oh yeah, good catch.
