### PR TITLE
Convert `WorldClock` to Appv2

### LINKED ISSUE #19101: Cmd (Ctrl but for Mac) does not work for adjusting inventory quantities or on world clock time
Cmd/⌘, the Mac equivalent of Ctrl, is missing support in the pf2e system. 

Holding Cmd should allow inventory quantities to be increased/reduce by 10, it does not.

Also holding Cmd should allow subtracting values on the World Clock, but they remain positive.

Unsure if there are other instances of Ctrl/Cmd usage that are specific to the pf2e system.

### PR DESCRIPTION
**Pull request by In3luki**
I'm not sure what to do about the bottom `hr`. Omitted it for now.

## Before
world-clock-before

## Light
world-clock-light

## Dark
world-clock-dark

### CODE REVIEW

**Comment by CarlosFdez** [comment]
I recall shark was trying to convert this, but I don't know how far he got.

**Comment by In3luki** [comment]
This is probably a going to get integrated with the new v13 calendar API. I just remembered that is a thing.
I'll keep this open and await sharks judgement.

File: src/module/apps/world-clock/app.ts [hunk 1]
```diff
@@ -8,19 +9,56 @@ interface WorldClockData {
     date: string;
     time: string;
     options?: object;
-    user: User;
+    user: typeof game.user;
```
Comment (stwlam) [inline src/module/apps/world-clock/app.ts:12]:
```suggestion
    user: UserPF2e;
```
This is a deeper type error we need to fix, but let's not hide it away like that.

File: src/module/apps/world-clock/app.ts [hunk 2]
```diff
@@ -8,19 +9,56 @@ interface WorldClockData {
...
+            width: 400,
+        },
+        window: {
+            title: "PF2E.WorldClock.Title",
+            controls: [
+                {
+                    action: "openSettings",
+                    icon: "fa-solid fa-gear",
+                    label: "PF2E.SETTINGS.Settings",
+                    visible: false,
```
[the remark this answers is not in the document]
Comment (In3luki) [reply src/module/apps/world-clock/app.ts]: Moved to `_getHeaderControls` for gm visibility.

File: src/module/apps/world-clock/app.ts [hunk 3]
```diff
@@ -8,19 +9,56 @@ interface WorldClockData {
...
     readonly animateDarkness = animateDarkness;
 
+    /** `#controlKeyHandlerFunction` bound to this instance to allow removal of the listeners. */
+    #controlKeyHandler: (event: KeyboardEvent) => void;
+
     constructor() {
         super();
         this.#initialize();
+        // Bind the handler function to this instance
+        this.#controlKeyHandler = this.#controlKeyHandlerFunction.bind(this);
```
[the remark this answers is not in the document]
Comment (In3luki) [reply src/module/apps/world-clock/app.ts]: I hopefully clarified the comment. Binding in `addEventListener` makes the function anonymous and breaks `removeEventListener`. Binding once and passing the reference works however.

[the remark this answers is not in the document]
Comment (CarlosFdez) [reply src/module/apps/world-clock/app.ts]: I see, because wrapping with () => {} would make it a new function reference and cause removal to fail. That said, I don't know if I like the idea of there being the function and the bound function both simultaneously available. Doing `#controlKeyHandler = () => {` sits better with me here.

[the remark this answers is not in the document]
Comment (In3luki) [reply src/module/apps/world-clock/app.ts]: Yeah that works too and is cleaner. Done.

**Comment by CarlosFdez** [comment]
gonna need to fix for post rebase, sorry, I forgot to check if this was ready to go first.

File: static/templates/system/world-clock.hbs [hunk 4]
```diff
@@ -1,40 +1,37 @@
...
+        <button type="button" data-action="advanceTime" data-advance-mode="{{sign}}" data-advance-time="600"><span class="sign">{{sign}}</span>{{localize "PF2E.WorldClock.Button.AddTenMinutes"}}</button>
+        <button type="button" data-action="advanceTime" data-advance-mode="{{sign}}" data-advance-time="3600"><span class="sign">{{sign}}</span>{{localize "PF2E.WorldClock.Button.AddOneHour"}}</button>
+        <button type="button" data-action="advanceTime" data-advance-mode="{{sign}}" data-advance-time="86400"><span class="sign">{{sign}}</span>{{localize "PF2E.WorldClock.Button.AddOneDay"}}</button>
+        <button type="button" data-action="advanceTime" data-advance-mode="{{sign}}" data-advance-time="604800"><span class="sign">{{sign}}</span>{{localize "PF2E.WorldClock.Button.AddOneWeek"}}</button>
+        <section class="time-of-day">
+            <button type="button" data-tooltip="PF2E.WorldClock.Button.TimeOfDay.Advance.Dawn" data-tooltip-direction="UP" data-action="advanceTime" data-advance-mode="{{sign}}" data-advance-time="dawn">
+                <span class="sign">{{sign}}</span><i class="fa-solid fa-sunrise"></i>
```
Comment (stwlam) [inline static/templates/system/world-clock.hbs]:
```suggestion
                <span class="sign">{{sign}}</span><i class="fa-solid fa-sunrise" inert></i>
```

File: static/templates/system/world-clock.hbs [hunk 5]
```diff
@@ -1,40 +1,37 @@
...
+            </button>
+            <button type="button" data-tooltip="PF2E.WorldClock.Button.TimeOfDay.Advance.Noon" data-tooltip-direction="UP" data-action="advanceTime" data-advance-mode="{{sign}}" data-advance-time="noon">
+                <span class="sign">{{sign}}</span><i class="fa-solid fa-sun"></i>
```
Comment (stwlam) [inline static/templates/system/world-clock.hbs]:
```suggestion
                <span class="sign">{{sign}}</span><i class="fa-solid fa-sun" inert></i>
```

File: static/templates/system/world-clock.hbs [hunk 6]
```diff
@@ -1,40 +1,37 @@
...
+            </button>
+            <button type="button" data-tooltip="PF2E.WorldClock.Button.TimeOfDay.Advance.Dusk" data-tooltip-direction="UP" data-action="advanceTime" data-advance-mode="{{sign}}" data-advance-time="dusk">
+                <span class="sign">{{sign}}</span><i class="fa-solid fa-sunset"></i>
```
Comment (stwlam) [inline static/templates/system/world-clock.hbs]:
```suggestion
                <span class="sign">{{sign}}</span><i class="fa-solid fa-sunset" inert></i>
```

File: static/templates/system/world-clock.hbs [hunk 7]
```diff
@@ -1,40 +1,37 @@
...
+            </button>
+            <button type="button" data-tooltip="PF2E.WorldClock.Button.TimeOfDay.Advance.Midnight" data-tooltip-direction="UP" data-action="advanceTime" data-advance-mode="{{sign}}" data-advance-time="midnight">
+                <span class="sign">{{sign}}</span><i class="fa-solid fa-moon-stars"></i>
```
Comment (stwlam) [inline static/templates/system/world-clock.hbs]:
```suggestion
                <span class="sign">{{sign}}</span><i class="fa-solid fa-moon-stars" inert></i>
```

File: src/styles/system/_world-clock.scss [hunk 8]
```diff
@@ -2,9 +2,10 @@
     section.window-content {
         font-size: 1rem;
 
-        h1 {
-            font-size: inherit;
+        .header {
```
Comment (CarlosFdez) [inline src/styles/system/_world-clock.scss]: any reason not to use an actual `<header>`?

Comment (In3luki) [reply src/styles/system/_world-clock.scss]: nope. now it's a header element.
