### PR TITLE
Fix retrieval of in-memory unarmed attacks for use in damage application

### LINKED ISSUE #20121: Add the `origin` flag to applied damage messages generated by character unarmed attacks.
Right now, the applied damage messages generated by a character unarmed attack (i.e. monk `Fist`) does not contains the `origin` flag while message generated by weapon strikes or npc strikes will have it.

This makes it impossible to retrieve the actor that dealt the damage nor the item associated with it.

Image
In the screenshot above, the first message is from a monk `Fist` strike while the second one was from a weapon strike.

### PR DESCRIPTION
**Pull request by stwlam**
- Closes #20121

### CODE REVIEW

File: src/module/chat-message/document.ts [hunk 1]
```diff
@@ -114,25 +114,27 @@ class ChatMessagePF2e extends ChatMessage {
...
-            const embeddedSpell = this.flags.pf2e.casting?.embeddedSpell;
-            if (actor && embeddedSpell) return new ItemProxyPF2e(embeddedSpell, { parent: actor });
-
-            const origin = this.flags.pf2e?.origin ?? null;
-            const item = origin?.uuid && !origin.uuid.startsWith("Compendium.") ? fromUuidSync(origin.uuid) : null;
-            return item instanceof ItemPF2e ? item : null;
-        })();
-        if (!item) return null;
+        const embeddedSpell = this.flags.pf2e.casting?.embeddedSpell;
+        if (actor && embeddedSpell) return new ItemProxyPF2e(embeddedSpell, { parent: actor });
```
Comment (CarlosFdez) [inline src/module/chat-message/document.ts]: This may need to be heightened or set with a variant. That's what the if is spell block later is for.

**Comment by CarlosFdez** [comment]
lgtm
