### PR TITLE
Fix regressions with rolling initiative

### LINKED ISSUE #7164: Initiative regressions introduced after 4.9.3
- Initiative can't be rolled from sheets without first adding a combatant separately
- Initiative rolled from sheets always shows the roll dialog
- The `initiativeStatistic` combatant flag is no longer recorded under any circumstance

### PR DESCRIPTION
**Pull request by In3luki**
- A combatant is created on rolling initiative if one doesn't exist already
- Roll params are passed from the character sheet again
- The `initiativeStatistic` is always set for characters and npcs

Closes #7164

### CODE REVIEW

File: src/module/encounter/document.ts [hunk 1]
```diff
@@ -145,6 +145,20 @@ class EncounterPF2e extends Combat {
         await this.update({ turn: this.turns.findIndex((c) => c.id === currentId) });
     }
 
+    override async setInitiative(id: string, value: number): Promise<void> {
+        const combatant = this.combatants.get(id, { strict: true });
+        if (combatant.actor?.isOfType("character", "npc")) {
+            return game.combat?.setMultipleInitiatives([
```
Comment (stwlam) [inline src/module/encounter/document.ts:151]:
```suggestion
            return this.setMultipleInitiatives([
```

File: src/module/encounter/combatant.ts [hunk 2]
```diff
@@ -36,6 +37,24 @@ class CombatantPF2e<
...
+        if (!game.combat) {
+            ui.notifications.error(game.i18n.localize("PF2E.Encounter.NoActiveEncounter"));
+            return null;
+        }
+        const token = actor.getActiveTokens().pop();
+        const existing = game.combat.combatants.find((combatant) => combatant.actor === actor);
+        if (existing) {
+            return existing;
+        } else if (token) {
+            await token.toggleCombat(game.combat);
```
Comment (stwlam) [inline src/module/encounter/combatant.ts:51]: Can we use `game.combat.createEmbeddedDocuments` here so that we can control rendering? Not rendering would be desirable in some callers' cases.

Comment (In3luki) [reply src/module/encounter/combatant.ts]: Updated. I've set it to render by default.

Comment (In3luki) [reply src/module/encounter/combatant.ts]: Also added the `sceneId` to the `Combatant` source. It seems to work without it but core `TokenLayer#toggleCombat` uses it so it's probably safer to include it.

File: src/module/apps/sidebar/chat-log.ts [hunk 3]
```diff
@@ -308,8 +306,16 @@ export class ChatLogPF2e extends ChatLog<ChatMessagePF2e> {
                         );
                         return;
                     }
+                    if (!actor) return;
+                    const combatant = await CombatantPF2e.fromActor(actor);
+                    if (!combatant) return;
+                    const value = message.rolls.at(0)?.total ?? 0;
+
+                    await game.combat!.setInitiative(combatant.id, value);
```
Comment (stwlam) [inline src/module/apps/sidebar/chat-log.ts:314]:
```suggestion
                    await combatant.encounter.setInitiative(combatant.id, value);
```

File: src/module/apps/sidebar/chat-log.ts [hunk 4]
```diff
@@ -308,8 +306,16 @@ export class ChatLogPF2e extends ChatLog<ChatMessagePF2e> {
                         );
                         return;
                     }
+                    if (!actor) return;
+                    const combatant = await CombatantPF2e.fromActor(actor);
+                    if (!combatant) return;
```
Comment (stwlam) [inline src/module/apps/sidebar/chat-log.ts:311]:
```suggestion
```

File: src/module/actor/initiative.ts [hunk 5]
```diff
@@ -60,9 +45,8 @@ class ActorInitiative {
         if (!roll) return null;
 
         // Update the tracker unless requested not to
-        const updateTracker = args.updateTracker ?? true;
         if (updateTracker) {
-            game.combat?.setInitiative(combatant.id, roll.total);
+            game.combat!.setInitiative(combatant.id, roll.total);
```
Comment (stwlam) [inline src/module/actor/initiative.ts:49]:
```suggestion
            combatant.encounter.setInitiative(combatant.id, roll.total);
```

File: src/module/chat-message/listeners/set-as-initiative.ts [hunk 6]
```diff
@@ -37,35 +35,22 @@ export const SetAsInitiative = {
...
                 if (!actor) return;
-
-                const combatant = ((): CombatantPF2e<EncounterPF2e> | null => {
-                    const existing = game.combat.combatants.find((c) => c.actor === actor);
-                    if (existing) return existing;
-                    ui.notifications.error(game.i18n.format("PF2E.Encounter.NotParticipating", { actor: actor.name }));
-                    return null;
-                })();
+                const combatant = await CombatantPF2e.fromActor(actor);
                 if (!combatant) return;
```
Comment (stwlam) [inline src/module/chat-message/listeners/set-as-initiative.ts:49]:
```suggestion
```

File: src/module/chat-message/listeners/set-as-initiative.ts [hunk 7]
```diff
@@ -37,35 +35,22 @@ export const SetAsInitiative = {
...
+                const value = message.rolls.at(0)?.total ?? 0;
 
-                const statistic =
-                    message.flags.pf2e.context?.domains.find(
-                        (s): s is SkillLongForm | "perception" =>
-                            setHasElement(SKILL_LONG_FORMS, s) || s === "perception"
-                    ) ?? null;
-                const value = message.rolls[0].total;
+                await game.combat!.setInitiative(combatant.id, value);
```
Comment (stwlam) [inline src/module/chat-message/listeners/set-as-initiative.ts:52]:
```suggestion
                await combatant?.encounter.setInitiative(combatant.id, value);
```

File: src/module/actor/initiative.ts [hunk 8]
```diff
@@ -31,25 +31,10 @@ class ActorInitiative {
...
-                return existing;
-            } else if (token) {
-                await token.toggleCombat(game.combat);
-                return token.combatant ?? null;
-            } else {
-                ui.notifications.error(game.i18n.format("PF2E.Encounter.NoTokenInScene", { actor: this.actor.name }));
-                return null;
-            }
-        })();
+        const combatant = await CombatantPF2e.fromActor(this.actor, updateTracker);
```
Comment (stwlam) [inline src/module/actor/initiative.ts:37]: The point of having the render option is so that we don't render twice, which will happen here.

File: src/module/apps/sidebar/chat-log.ts [hunk 9]
```diff
@@ -308,8 +306,16 @@ export class ChatLogPF2e extends ChatLog<ChatMessagePF2e> {
                         );
                         return;
                     }
+                    if (!actor) return;
+                    const combatant = await CombatantPF2e.fromActor(actor);
```
Comment (stwlam) [inline src/module/apps/sidebar/chat-log.ts:310]:
```suggestion
                    const combatant = await CombatantPF2e.fromActor(actor, false);
```

File: src/module/apps/sidebar/chat-log.ts (hunk 4 above)
Comment (In3luki) [reply src/module/apps/sidebar/chat-log.ts:311]: This would always show the notification that the initiative was set even if there is no active encounter.
